### PR TITLE
[ FIX #51, #52 & #53 ] Update Python, NodeJS & Java BDK to API 0.2

### LINKED ISSUE #51: Update Node.js BDK to Beacon 0.2 API
Adapter: https://github.com/mcupak/beacon-of-beacons/tree/master/beacon-adapters/beacon-nodejs
Docs: http://mcupak.github.io/beacon-of-beacons/beacons.html#nodejs
API 0.2: https://docs.google.com/document/d/1hFVqmPDKAs2Tacqta98oIPqUOKlHghmuJD8DtYLQFKw/edit?usp=sharing

Change /query and /info endpoints to generate data in the form according to the new API version.

### LINKED ISSUE #53: Update Python BDK to Beacon 0.2 API
Adapter: https://github.com/mcupak/beacon-of-beacons/tree/master/beacon-adapters/beacon-python
Docs: http://mcupak.github.io/beacon-of-beacons/beacons.html#python
API 0.2: https://docs.google.com/document/d/1hFVqmPDKAs2Tacqta98oIPqUOKlHghmuJD8DtYLQFKw/edit?usp=sharing

Change /query and /info endpoints to generate data in the form according to the new API version.

### PR DESCRIPTION
**Pull request by rohankatyal29**

### CODE REVIEW

**Comment by mcupak** [comment]
beacon-java contains tests which are broken in this PR (not compilable) - @rohankatyal29, can you fix that?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project beacon-java: Compilation failure: Compilation failure:
[ERROR] /var/tmp/beacon-of-beacons/beacon-adapters/beacon-java/src/test/java/com/dnastack/beacon/rest/BeaconResourceTest.java:[113,33] error: incompatible types: ResponseResource cannot be converted to boolean
[ERROR] /var/tmp/beacon-of-beacons/beacon-adapters/beacon-java/src/test/java/com/dnastack/beacon/rest/BeaconResourceTest.java:[122,34] error: incompatible types: ResponseResource cannot be converted to boolean

**Comment by mcupak** [comment]
Also, there are conflicts in this PR - could you rebase it to the current master?

**Comment by mcupak** [comment]
Ad beacon-python:
- README needs to be updated with the new context path
- Can you add a sample welcome page to http://127.0.0.1:5000/beacon-python/?

**Comment by mcupak** [comment]
Ad beacon-nodejs:
- README needs to be updated with the new context path
- "exists" should be boolean, not string
- /query should only include ID of the beacon, not the full object (see the spec)

**Comment by mcupak** [comment]
Ad all the beacons:

The "error" field should only be generated if there is a problem, i.e. if "exists=null". Can you make it behave so that the "error" field is omitted if a valid query (i.e. all the required parameters are specified) is issued. If any of the required parameters are missing, you should return exists=null and the "error" with a message indicating an incomplete query. For the beacon-python beacon, this replies returning this kind of message instead of internal server error.

**Comment by mcupak** [comment]
Ad beacon-java:
- same note about the README update
- the API also produces XML (by design), which behaves kind of weird now (lists are visible as simple fields), e.g.:
```xml
<beacon><api>0.1/0.2</api><auth>oauth2</auth><datasets><allele>allele string</allele><chromosome>chromosome id</chromosome><dataset_id>dataset Id</dataset_id><position>1</position><reference>genome Id</reference></datasets><description>sample beacon</description><email>beacon@dnastack.com</email><homepage>http://dnastack.com/ga4gh/bob/</homepage><id>foo</id><name>bar</name><organization>org</organization><queries><description>description</description><id>id</id><reference>reference</reference></queries></beacon>
```
- specifying /query (without any parameters) shows NPE instead of a proper response
- exists should be boolean

**Comment by rohankatyal29** [comment]
1 Beacon-python already has a welcome page

2 The documentation says that the "exists" field can have four possible values and is a string: 
screen shot 2015-03-17 at 8 31 23 am

Do you want me to change it to Boolean in all the beacons?

**Comment by mcupak** [comment]
You're right, I see "http://127.0.0.1:5000/beacon-python" serves the welcome page, but "http://127.0.0.1:5000/beacon-python/" doesn't, I did not notice that.

Sorry about the "exists" confusion, that's my fault. It should be Boolean (i.e. true/false/null) actually, this change was made recently and is not reflected in the Google doc. If you could change it to Boolean please, that would be great.

Thanks!

**Comment by rohankatyal29** [comment]
Not a problem! 

Will take care of the all changes :+1:

**Comment by mcupak** [comment]
Btw, for all intents and purposes, field=null and field not specified are interchangeable.

**Comment by rohankatyal29** [comment]
okay, got it

**Comment by rohankatyal29** [comment]
Beacon-Java: 

XML response: 
screen shot 2015-03-17 at 6 39 43 pm

JSON response:
screen shot 2015-03-17 at 6 40 11 pm

Isn't this fine?

**Comment by rohankatyal29** [comment]
For beacon java: 

I have made the necessary modifications to the tests. When I try to run the tests: 

With wildfly working on standalone mode I get this:
screen shot 2015-03-17 at 6 45 58 pm

With wildfly not deployed I get this:
screen shot 2015-03-17 at 6 50 06 pm

**Comment by rohankatyal29** [comment]
Beacon-Java: 

XML response: 
screen shot 2015-03-17 at 6 53 48 pm

JSON response:
screen shot 2015-03-17 at 6 54 25 pm


Is this fine?

**Comment by rohankatyal29** [comment]
/query now returns:
screen shot 2015-03-17 at 6 56 12 pm

**Comment by mcupak** [comment]
First comment - both snippets show JSON?

Second comment - looks good!

**Comment by rohankatyal29** [comment]
First comment - that was the XML output from the postman extension, it does look a lot like JSON though
screen shot 2015-03-17 at 9 04 56 pm

**Comment by mcupak** [comment]
Yeah, this looks fine. The problem I referred to originally was related to /info, specifically:

```xml
<datasets>
<allele>allele string</allele>
<chromosome>chromosome id</chromosome>
<dataset_id>dataset Id</dataset_id>
<position>1</position>
<reference>genome Id</reference>
</datasets>
```

```xml
<queries>
<description>description</description>
<id>id</id>
<reference>reference</reference>
</queries>
```

Note that queries and datasets seem to be interchanged and they seem to contain a single entity as opposed to a list of entities.

**Comment by rohankatyal29** [comment]
I have taken care of all the above mentioned pointers. The only thing is that the beacon-java tests aren't passing, can you please look into it.

**Comment by mcupak** [comment]
Will do, thanks!

**Pull request merged**
