### PR TITLE
[FIXED #44] added list of beacons in the client

### LINKED ISSUE #44: List beacons in the client
Add a page providing a list of beacons, their organizations and aggregate flag on a separate page in the client.

### PR DESCRIPTION
**Pull request by rohankatyal29**
Let me know if any other changes are required
screen shot 2015-03-10 at 8 14 13 pm

### CODE REVIEW

**Comment by mcupak** [comment]
Looks nice, thanks!

A few recommendations before we merge this:
- Instead of true/false in the UI, use more graphic yes/no indicators - I suggest the ones from the query results page, for consistency.
- Remove eclipse-specific files from the PR (.project, .setttings/* etc.). Add them to .gitignore.
- Can you remove beacon-list-map.js? I don't think it's needed, you have everything necessary in bob-api.js, right?

**Comment by rohankatyal29** [comment]
These files got committed by mistake,will take care of those right away.
Which indicators are you suggesting?

**Comment by rohankatyal29** [comment]
Is this what you meant? 
screen shot 2015-03-10 at 9 25 40 pm

**Comment by mcupak** [comment]
Exactly. http://dnastack.com/ga4gh/bob/query.html?beacon=all&ref=all&chrom=2&pos=179612321&alt=T

**Comment by mcupak** [comment]
Not sure if you closed this intentionally. It's not merged yet, you can append changes to an existing PR.

**Comment by rohankatyal29** [comment]
I have created a new pull right, something got messed up in my local

**Pull request closed without merging**
